{{- if .Values.externalSecrets.enabled }}
{{- range $name, $entries := .Values.externalSecrets.stores }}
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "image-resizer.fullname" $ }}
  labels:
    {{- include "image-resizer.labels" $ | nindent 4 }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ $name }}
    kind: SecretStore
  target:
    name: {{ include "image-resizer.fullname" $ }}
  data:
  {{- range $name, $keys := $entries }}
  {{- range $source, $destination := $keys }}
  - secretKey: {{ $destination }}
    remoteRef:
      key: {{ $name }}
      property: {{ $source }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
