{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mokta
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
{{- if .Values.ingress.annotations }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
{{- if .Values.ingress.redirectHttpToHttps }}
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ssl-redirect
              port:
                name: use-annotation
{{- end }}
{{- if .Values.ingress.paths }}
{{ toYaml .Values.ingress.paths | indent 8 }}
{{- end }}
{{- end }}
