apiVersion: v1
kind: Service
metadata:
  name: mokta
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 4001
      targetPort: http
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
