---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postcoder-proxy.fullname" . }}
  labels:
    {{- include "postcoder-proxy.labels" . | nindent 4 }}
data:
{{ toYaml .Values.env | indent 2 }}
