image:
  repository: 979633842206.dkr.ecr.eu-west-1.amazonaws.com/mokta
  tag: latest

env:
  SAFE_HOSTS: https://*.qa.citizensadvice.org.uk
  OKTA_EMBED_LINK: https://cadev.oktapreview.com/home/oidc_client/0oa1hwcw23bWFpbHf0h8/aln5z7uhkbM6y7bMy0g7

annotations:

ingress:
  enabled: true
  # DISABLED BY DEFAULT, WILL FAIL TESTINGING IF ENABLED
  # ENABLE THIS WHEN DEPLOYING USING --set ingress.enabled=true
  hostname: mokta.devops.citizensadvice.org.uk
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/tags: Environment=review,Product=mokta
    alb.ingress.kubernetes.io/healthcheck-path: /status
  paths:
    - path: /
      pathType: Prefix
      backend:
        service:
          name: mokta
          port:
            name: http
