name: Publish Charts

on:
  push

jobs:
  validate-charts:
    runs-on: ubuntu-22.04

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: pip3 install pyyaml

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      - name: Add Helm Repos
        run:  helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Lint Charts
        run: ct lint --all --check-version-increment=false --validate-maintainers=false

      - name: Validate Charts
        run: python3 bin/validate.py
        env:
          CHARTS_DIR: charts

  test-charts:
    name: test-charts
    runs-on: ubuntu-latest
    needs: validate-charts
    strategy:
      matrix:
        k8s:
          - v1.24.7
          - v1.25.3
          - v1.26.0

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1.0.3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Add Helm Repos
        run:  helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@v1.3.0
        with:
          node_image: kindest/node:${{ matrix.k8s }}

      - name: Run chart-testing (install) ${{ matrix.k8s }}
        run: |
          ct install --all

  publish-charts:
    runs-on: ubuntu-22.04
    needs: test-charts
    if: github.ref_name == 'main'
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Add Helm Repos
        run:  helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Publish Charts
        uses: helm/chart-releaser-action@v1.5.0
        with:
          version: v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
